dask:
    client:
        dashboard_address: 8786
        silence_logs: 50
        n_workers: 2
        threads_per_worker: 6
        memory_limit: 16GB
    array.slicing.split_large_chunks: False
    local:
        num_workers: 8
        scheduler: threads

logging:
    formatters:
        default:
            format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class : logging.StreamHandler
            formatter: default
            level : DEBUG
    loggers:
        workflow:
            level: INFO
            propagate: False
            handlers: [console]
        xscen:
            level: DEBUG
            propagate: False
            handlers: [console]
        xscen.io:
            level: DEBUG
        xscen.indicators:
            level: ERROR
    root:
        level: INFO
        handlers: [console]

scr_utils:
    measure_time:
        cpu: True
    send_mail:
        to: bourgault.pascal@ouranos.ca
    send_mail_on_exit:
        msg_ok: Toutes les étapes demandées ont été complétées.
        msg_err: Une erreur est survenue durant le traitement.
        on_error_only: True

extraction:
    variables:
        tasmax: D
        tasmin: D
        pr: D

project:
    id: ESPO-R5
    title: Data generated for ESPO-R5
    version: v1.0

custom:
    variables: ['tasmax', 'tasmin', 'pr']
    region: middle
    bbox:
        north:
            lon_bnds: [-147.55, -52.65]
            lat_bnds: [74.25, 59.25]
        middle:
            lon_bnds: [-147.55, -52.65]
            lat_bnds: [59.25, 44.25]
        south:
            lon_bnds: [-147.55, -52.65]
            lat_bnds: [44.25, 19.25]
        fixnm:
            lon_bnds: [-147.55, -52.65]
            lat_bnds: [59.35, 59.15]
        fixms:
            lon_bnds: [-147.55, -52.65]
            lat_bnds: [44.35, 44.15]
        fixs:
            lon_bnds: [-147.55, -52.65]
            lat_bnds: [19.35, 19.15]
    chunks:
        lat: 20  # if stack_drop_nans is False
        lon: 20  # idem
        loc: 600 # if stack_drop_nans is True, for 126 Mo chunks
        time : -1
    stack_drop_nans: True
    out_chunks:  # This gives ~14 Mo per chunk. netCDFs will be yearly so ~3.5 Mo
        lat: 50
        lon: 50
        time: 4year
    maximal_calendar: noleap
    reference_period:
        - 1981
        - 2010
    target_period:
        - 1951
        - 2100
    future_period:
        - 2071
        - 2100
    final_attrs_names:
        - bias_adjustment
        - cell_methods
        - coordinates
        - history
        - long_name
        - standard_name
        - units
    attrs:
        global:
            Conventions: CF-1.9
            title: ESPO-R5 v1.0.0 - {simulation} {scenario} - Region {region}
            institution: Ouranos
            source: |
                Regridded on the grid of ERA5-Land, then bias-adjusted with detrended
                quantile mapping on a day-of-year basis with a window of 31 days, LOESS
                detrending and 50 quantiles (0.01 to 0.99). The reference was ERA5-Land
                over the 1981-2010 period. Tasmax, dtr and pr were adjusted, tasmin was
                computed from tasmax and dtr after the adjustment.
            redistribution: Redistribution prohibited. For internal use only.
            version: "1.0.0"
        tasmax:
            standard_name: air_temperature
            long_name: Maximal daily temperature
            cell_methods: "time: maximum within days"
        tasmin:
            standard_name: air_temperature
            long_name: Minimal daily temperature
            cell_methods: "time: minimum within days"
        pr:
            standard_name: precipitation_flux
            long_name: Mean daily precipitation flux
            cell_methods: "time: mean within days"
biasadjust:
    train:
        reference_period:
            - 1981
            - 2010
        maximal_calendar: noleap
    adjust:
        target_period:
            - 1951
            - 2100
        bias_adjust_institution: Ouranos
        bias_adjust_project: ESPO-R5
    variables:
        dtr:
            method: DetrendedQuantileMapping
            group:
                group: time.dayofyear
                window: 31
            xclim_train_args:
                kind: "*"
                nquantiles: 50
            adjust:
                detrend:
                    LoessDetrend:
                        f: 0.2
                        niter: 1
                        d: 0
                        weights: tricube
                interp: nearest
                extrapolation: constant
        tasmax:
            method: DetrendedQuantileMapping
            group:
                group: time.dayofyear
                window: 31
            xclim_train_args:
                kind: "+"
                nquantiles: 50
            adjust:
                detrend:
                    LoessDetrend:
                        f: 0.2
                        niter: 1
                        d: 0
                        weights: tricube
                interp: nearest
                extrapolation: constant
        pr:
            method: DetrendedQuantileMapping
            group:
                group: time.dayofyear
                window: 31
            adapt_freq:
                thresh: 1 mm d-1
            jitter_under:
                thresh: 0.01 mm d-1
            xclim_train_args:
                kind: "*"
                nquantiles: 50
            adjust:
                detrend:
                    LoessDetrend:
                        f: 0.2
                        niter: 1
                        d: 0
                        weights: tricube
                interp: nearest
                extrapolation: constant
regridding:
    regrid:
        method: bilinear
        unmapped_to_nan: True

indicators:
    work_on_local_copy: False
    filename_template: "{driving_institution}_{driving_model}_{institution}_{source}_{experiment}_{xrfreq}_1950-2100.zarr"
    ref_template: "ERA5-land_obs_{xrfreq}_1950-2100.zarr"
